version: '3.9'

services:
  app-finance:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
    volumes:
      - .:/code
    depends_on:
      - dbfinance
    restart: always
    networks:
      - app-network-finance

  dbfinance:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:${DB_PORT}"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network-finance

volumes:
  db_data:


networks:
  app-network-finance:
