"""transaction_id to id_split

Revision ID: 2cd8e679da52
Revises: 2f22df20c811
Create Date: 2025-03-03 02:43:52.206017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2cd8e679da52'
down_revision: Union[str, None] = '2f22df20c811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('splits', sa.Column('id_transaction', sa.Integer(), nullable=False))
    op.drop_constraint('splits_ibfk_2', 'splits', type_='foreignkey')
    op.create_foreign_key(None, 'splits', 'transactions', ['id_transaction'], ['id'])
    op.drop_column('splits', 'transaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('splits', sa.Column('transaction_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'splits', type_='foreignkey')
    op.create_foreign_key('splits_ibfk_2', 'splits', 'transactions', ['transaction_id'], ['id'])
    op.drop_column('splits', 'id_transaction')
    # ### end Alembic commands ###
