"""update split.category_id to split.id_category

Revision ID: 37de65f96d90
Revises: e1596eb43c75
Create Date: 2025-06-03 16:53:34.049469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '37de65f96d90'
down_revision: Union[str, None] = 'e1596eb43c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('splits', sa.Column('id_category', sa.Integer(), nullable=True))
    op.drop_constraint('splits_ibfk_1', 'splits', type_='foreignkey')
    op.create_foreign_key(None, 'splits', 'categories', ['id_category'], ['id'])
    op.drop_column('splits', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('splits', sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'splits', type_='foreignkey')
    op.create_foreign_key('splits_ibfk_1', 'splits', 'categories', ['category_id'], ['id'])
    op.drop_column('splits', 'id_category')
    # ### end Alembic commands ###
